# Generated by Django 5.2.13 on 2026-04-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_base_url', models.URLField(default='http://127.0.0.1:8000')),
                ('default_from_name', models.CharField(blank=True, max_length=100)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('default_reply_to', models.EmailField(blank=True, max_length=254)),
                ('email_backend', models.CharField(choices=[('console', 'Console (print to server log)'), ('smtp', 'SMTP (real delivery)'), ('file', 'File (save to /tmp)')], default='console', max_length=20)),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_timeout', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
    ]
